name: Publish to Docker Hub
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Alexandria to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: raisultan/alexandria
          tag_with_ref: true
